baseURL = 'http://nikki.sabanium.me'
languageCode = 'ja-JP'
defaultContentLanguage = 'ja'
title = 'NIKKI'
theme = 'PaperMod'
publishDir = 'docs/'

[params]
ShowPostNavLinks = true
author = 'sabanium'
[params.homeInfoParams]
Title = 'NIKKI'
Content = "くるりのアルバムではアンテナが一番好き。"
[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/n3608e14011'
  
[menu]
[[menu.main]]
  identifier = 'About' 
  name = 'About'
  url = '/about/'

[[menu.main]]
  identifier = 'Tags' 
  name = 'Tags'
  url = '/tags/'

[[menu.main]]
  identifier = 'Archives' 
  name = 'Archive'
  url = '/archives/'
